global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sysguard'
    static_configs:
      - targets: ['sysguard:9000']
    metrics_path: /metrics
    scrape_interval: 30s
